version: "3.8"

services:
  mongodb:
    container_name: mongodb
    image: mongo:4.2
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pass
    networks: 
      - mongodb_network
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data/db
   
  
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    depends_on:
      - mongodb
    networks: 
      - mongodb_network
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass12345
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    ports:
      - '8081:8081'
    volumes: 
     - mongodb-data:/data/db

volumes:
  mongodb-data:
    name: mongodb-data

networks:
  mongodb_network:
    name: mongodb_network

